spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ximusunny/springcloud-bus-learn.git
          username:
          password:
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  instance:
    hostname: 127.0.0.1
    appname: config-server
  client:
    allow-redirects: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
